name: OBET-NGROK-VPS
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/b342PueNQ29/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip
    - name: Authenticate Ngrok
      run: .\ngrok\ngrok.exe authtoken 3DAl4o6ASNnyJianbboXorSyj2E_3zi3EFadjDsDcoMB2RMiD
    - name: Aktifkan RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Create User
      run: |
        net user runneradmin OBETganteng123! /add
        net localgroup administrators runneradmin /add
    - name: Buka Terowongan RDP
      run: start .\ngrok\ngrok.exe tcp 3389
    - name: Cek Alamat RDP
      run: |
        $response = curl http://localhost:4040/api/tunnels | ConvertFrom-Json
        Write-Host "ALAMAT RDP LO ADALAH:"
        $response.tunnels[0].public_url
    - name: Jaga VPS
      run: Start-Sleep -Seconds 21600
